//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnswerPoortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int id { get; set; }
        public string text { get; set; }
        public int num { get; set; }
        public bool isCorrect { get; set; }
        public string index { get; set; }
        public int idQuestion { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
