//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnswerPoortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int id { get; set; }
        public int answerPriceK { get; set; }
        public int unlockPriceM { get; set; }
        public int evaluationPriceE { get; set; }
        public int silverPriceS { get; set; }
        public int goldPriceG { get; set; }
        public int platinumPriceP { get; set; }
    }
}
