//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnswerPoortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public int tokenNum { get; set; }
        public int tokenPrice { get; set; }
        public string status { get; set; }
        public int idAccount { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
