//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnswerPoortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionCopy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionCopy()
        {
            this.AnswerCopies = new HashSet<AnswerCopy>();
            this.Responses = new HashSet<Response>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string text { get; set; }
        public byte[] pic_path { get; set; }
        public bool status { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> lockDate { get; set; }
        public int idAccount { get; set; }
        public int idOriginal { get; set; }
        public int idChannel { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerCopy> AnswerCopies { get; set; }
        public virtual Channel Channel { get; set; }
        public virtual Question Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Response> Responses { get; set; }
    }
}
