//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnswerPoortal.Models

    
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answers = new List<Answer>();
            this.QuestionCopies = new List<QuestionCopy>();
        }

        public int id { get; set; }
        [Display(Name = "Title")]
        public string title { get; set; }
        [Display(Name = "Text")]
        public string text { get; set; }
        [Display(Name = "Picture")]
        public byte[] pic_path { get; set; }
        [Display(Name = "Locked")]
        public bool status { get; set; }
        [Display(Name = "Date Created")]
        public System.DateTime creationDate { get; set; }
        [Display(Name = "Date Locked")]
        public Nullable<System.DateTime> lockDate { get; set; }
        public int idAccount { get; set; }

        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Answer> Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<QuestionCopy> QuestionCopies { get; set; }
    }
}
